#!/usr/bin/python

import sys
from LexicalAnalyzer.LexicalAnalyzer import *
from SemanticAnalyzer import *

fl = FileAccessManager(sys.argv[1])
analyzer = LexicalAnalyzer(fl)
result = analyzer.analyze()

semantizer = SemanticAnalyzer(result)
print semantizer.Run()

